[project]
name = "keyboard-game"
version = "2.0.0"
description = "键盘打字竞速游戏"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.0.0",
    "httpx>=0.25.0",
    "selenium>=4.15.0",
    "requests>=2.31.0",
]
